export enum ESymbolType {
    ad = 'ADR',
    gdr = 'GDR',
    re = 'REIT',
    ce = 'Closed end fund',
    si = 'Secondary Issue',
    lp = 'Limited Partnerships',
    cs = 'Common Stock',
    et = 'ETF',
    wt = 'Warrant',
    rt = 'Right',
    oef = 'Open Ended Fund',
    cef = 'Closed Ended Fund',
    ps = 'Preferred Stock',
    ut = 'Unit',
    struct = 'Structured Product',
}
